/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const OrderStatus = IDL.Variant({
  'Delivered' : IDL.Null,
  'Confirmed' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Shipped' : IDL.Null,
  'Pending' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'COD' : IDL.Null,
  'Online' : IDL.Null,
});
export const Time = IDL.Int;
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'user' : IDL.Principal,
  'orderDate' : Time,
  'address' : IDL.Text,
  'items' : IDL.Vec(CartItem),
});
export const Category = IDL.Variant({
  'Budget' : IDL.Null,
  'Luxury' : IDL.Null,
  'Sport' : IDL.Null,
  'Kids' : IDL.Null,
  'Fitness' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'rating' : IDL.Float64,
  'price' : IDL.Nat,
});
export const ReturnRequest = IDL.Record({
  'orderId' : IDL.Nat,
  'requestDate' : Time,
  'reason' : IDL.Text,
});
export const Review = IDL.Record({
  'user' : IDL.Principal,
  'productId' : IDL.Nat,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addReview' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'addToWishlist' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getReturnRequests' : IDL.Func([], [IDL.Vec(ReturnRequest)], ['query']),
  'getReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWishlist' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([IDL.Vec(CartItem), IDL.Text, PaymentMethod], [], []),
  'removeCartItem' : IDL.Func([IDL.Nat], [], []),
  'removeFromWishlist' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedProducts' : IDL.Func([], [], []),
  'submitReturnRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateCartItem' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CartItem = IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat });
  const OrderStatus = IDL.Variant({
    'Delivered' : IDL.Null,
    'Confirmed' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Shipped' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({ 'COD' : IDL.Null, 'Online' : IDL.Null });
  const Time = IDL.Int;
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'paymentMethod' : PaymentMethod,
    'user' : IDL.Principal,
    'orderDate' : Time,
    'address' : IDL.Text,
    'items' : IDL.Vec(CartItem),
  });
  const Category = IDL.Variant({
    'Budget' : IDL.Null,
    'Luxury' : IDL.Null,
    'Sport' : IDL.Null,
    'Kids' : IDL.Null,
    'Fitness' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'rating' : IDL.Float64,
    'price' : IDL.Nat,
  });
  const ReturnRequest = IDL.Record({
    'orderId' : IDL.Nat,
    'requestDate' : Time,
    'reason' : IDL.Text,
  });
  const Review = IDL.Record({
    'user' : IDL.Principal,
    'productId' : IDL.Nat,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addReview' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'addToWishlist' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getReturnRequests' : IDL.Func([], [IDL.Vec(ReturnRequest)], ['query']),
    'getReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWishlist' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Vec(CartItem), IDL.Text, PaymentMethod],
        [],
        [],
      ),
    'removeCartItem' : IDL.Func([IDL.Nat], [], []),
    'removeFromWishlist' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedProducts' : IDL.Func([], [], []),
    'submitReturnRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateCartItem' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };