/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : bigint, 'quantity' : bigint }
export type Category = { 'Budget' : null } |
  { 'Luxury' : null } |
  { 'Sport' : null } |
  { 'Kids' : null } |
  { 'Fitness' : null };
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'user' : Principal,
  'orderDate' : Time,
  'address' : string,
  'items' : Array<CartItem>,
}
export type OrderStatus = { 'Delivered' : null } |
  { 'Confirmed' : null } |
  { 'Cancelled' : null } |
  { 'Shipped' : null } |
  { 'Pending' : null };
export type PaymentMethod = { 'COD' : null } |
  { 'Online' : null };
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : Category,
  'rating' : number,
  'price' : bigint,
}
export interface ReturnRequest {
  'orderId' : bigint,
  'requestDate' : Time,
  'reason' : string,
}
export interface Review {
  'user' : Principal,
  'productId' : bigint,
  'comment' : string,
  'rating' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addReview' : ActorMethod<[bigint, bigint, string], undefined>,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'addToWishlist' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getReturnRequests' : ActorMethod<[], Array<ReturnRequest>>,
  'getReviews' : ActorMethod<[bigint], Array<Review>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWishlist' : ActorMethod<[], Array<bigint>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<
    [Array<CartItem>, string, PaymentMethod],
    undefined
  >,
  'removeCartItem' : ActorMethod<[bigint], undefined>,
  'removeFromWishlist' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedProducts' : ActorMethod<[], undefined>,
  'submitReturnRequest' : ActorMethod<[bigint, string], undefined>,
  'updateCartItem' : ActorMethod<[bigint, bigint], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];